
# Site settings
title: design thoughts and other thoughts
description: Felix's graphic design class blog
baseurl: "/blogau" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "http://felixnw.github.io/blogau" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
